# Generated by Django 3.2.5 on 2021-07-10 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
